#!/bin/bash

# check if git is installed
if ! command -v git &> /dev/null; then
    echo "git is not installed"
    exit 1
fi

# check if convco is installed
if ! command -v convco &> /dev/null; then
    echo "convco is not installed"
    exit 1
fi

echo "Checking for conventional commits"

# get current commit hash
COMMIT_HASH_CURRENT=$(git rev-parse HEAD)

# generate changelog
CONVENTIONAL_COMMITS=$(convco check --merges --ignore-reverts -n 1)

if echo "$CONVENTIONAL_COMMITS" | grep -qi "fail"; then
    echo "Failures found in conventional commit"
    exit 1
fi

echo "No failures found in conventional commits"
exit 0

