name: manifest-container

on:
  workflow_call:
    inputs:
      containerName:
        description: "Name of the container for which to build/push manifest"
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  build-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Login to Docker Hub to Avoid Rate Limiting
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Manifest
        run: |
          # E.g., run your own script that does the "docker manifest create/push"
          ./scripts/movement/manifest ${{ inputs.containerName }} 