name: Conventional Commit Check
run-name: Checking ${{ github.sha }} for conventional commits

on:
  pull_request:
    types:
    - labeled
    - opened
    - synchronize
  push:
    branches:
      - '**'
      - '!main' 


jobs:
  conventional-commit-check:
    runs-on: ubuntu-latest
    steps:
        
      # check out repository
      - name: Check out repository
        uses: actions/checkout@v4

      # install cargo
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # install convco
      - name: Install convco
        run: cargo install convco

      # check for conventional commits  
      - name: Check for conventional commits
        run: scripts/ops/conv-commit-check.sh