name: Semantic Release
run-name: ${{ (github.event.inputs.dry_run == 'true') && 'Semantic Release [DRY RUN]' || 'Semantic Release' }}

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: "The type of bump to perform"
        type: choice
        options:
          - auto
          - patch
          - minor
          - major
        required: false
        default: auto
      dry_run:
        description: "Run semantic-release in dry-run mode"
        type: choice
        options:
          - true
          - false
        required: false
        default: 'true'

jobs:
  create-release:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Cocogitto
        run: |
          cargo install cocogitto --locked
          cargo install cargo-edit --locked

      - name: Configure Git
        run: |
          git config --global user.name "Infrastructure[bot]"
          git config --global user.email "infrastructure@movementlabs.xyz"

      - name: Pull tags
        run: |
          git fetch --tags

      - name: Bump Version
        run: |
          ./scripts/ops/semantic-release ${{ inputs.bump_type }} ${{ inputs.dry_run }}
