name: Semantic Release
run-name: ${{ (github.event.inputs.dry_run == 'true') && 'Semantic Release [DRY RUN]' || 'Semantic Release' }}

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run semantic-release in dry-run mode"
        type: choice
        options:
          - true
          - false
        required: false
        default: 'true'

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Cocogitto
        run: |
          cargo install cocogitto --locked
          cargo install convco
          cargo install cargo-edit

      - name: Configure Git
        run: |
          git config --global user.name "Infrastructure[bot]"
          git config --global user.email "infrastructure@movementlabs.xyz"

      - name: Bump Version
        run: |
          ./scripts/ops/semantic-release ${{ inputs.bump_type }}
