name: Cargo Release

on:
  workflow_dispatch: # Allows manual/matrix triggering

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Cocogitto
        run: |
          cargo install cocogitto --locked
          cargo install cargo-edit

      - name: Configure Git
        run: |
          git config --global user.name "Infrastructure[bot]"
          git config --global user.email "infrastructure@movementlabs.xyz"

          
      - name: Bump Version
        run: |
          cog bump --auto
          # git push --follow-tags
